export interface YouTubeIntelligenceFlags {
  YOUTUBE_INTELLIGENCE_ENABLED: boolean;
  YOUTUBE_INTELLIGENCE_LIVE_INGEST: boolean;
  YOUTUBE_REMOTE_VIDEO_DOWNLOAD_ENABLED: boolean;
  YOUTUBE_AUDIO_DOWNLOAD_ENABLED: boolean;
  YOUTUBE_COOKIE_AUTH_ENABLED: boolean;
  YOUTUBE_REMOTE_FRAME_EXTRACTION_ENABLED: boolean;
  YOUTUBE_INTELLIGENCE_LLM_ENABLED: boolean;
  YOUTUBE_INTELLIGENCE_PRODUCTION_BRIDGE_ENABLED: boolean;
}

export const DEFAULT_YOUTUBE_INTELLIGENCE_FLAGS: Readonly<YouTubeIntelligenceFlags> =
  Object.freeze({
    YOUTUBE_INTELLIGENCE_ENABLED: false,
    YOUTUBE_INTELLIGENCE_LIVE_INGEST: false,
    YOUTUBE_REMOTE_VIDEO_DOWNLOAD_ENABLED: false,
    YOUTUBE_AUDIO_DOWNLOAD_ENABLED: false,
    YOUTUBE_COOKIE_AUTH_ENABLED: false,
    YOUTUBE_REMOTE_FRAME_EXTRACTION_ENABLED: false,
    YOUTUBE_INTELLIGENCE_LLM_ENABLED: false,
    YOUTUBE_INTELLIGENCE_PRODUCTION_BRIDGE_ENABLED: false,
  });

const UNSAFE_FLAG_NAMES = [
  "YOUTUBE_INTELLIGENCE_LIVE_INGEST",
  "YOUTUBE_REMOTE_VIDEO_DOWNLOAD_ENABLED",
  "YOUTUBE_AUDIO_DOWNLOAD_ENABLED",
  "YOUTUBE_COOKIE_AUTH_ENABLED",
  "YOUTUBE_REMOTE_FRAME_EXTRACTION_ENABLED",
  "YOUTUBE_INTELLIGENCE_LLM_ENABLED",
  "YOUTUBE_INTELLIGENCE_PRODUCTION_BRIDGE_ENABLED",
] as const satisfies ReadonlyArray<keyof YouTubeIntelligenceFlags>;

export function assertSyntheticFixtureOnly(
  flags: Readonly<YouTubeIntelligenceFlags> = DEFAULT_YOUTUBE_INTELLIGENCE_FLAGS,
): void {
  const enabledUnsafeFlag = UNSAFE_FLAG_NAMES.find((name) => flags[name]);
  if (enabledUnsafeFlag) {
    throw new Error(`YOUTUBE_INTELLIGENCE_RESEARCH_BOUNDARY_BLOCKED:${enabledUnsafeFlag}`);
  }
}
