import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import { acquireProcessLock, DEFAULT_QUEUE_SCHEDULER_SETTINGS, LocalQueueRepository, QUEUE_SCHEDULER_FLAGS, runNextBatch, type QueueVideoRuntimeReadiness } from "../../src/lib/queue-scheduler";
import type { RankedLiveProduct } from "../../src/lib/live-product-video";
import { createTestCodexEvidence } from "./testCodexEvidence";

const roots: string[] = [];
afterEach(async () => Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))));
async function repository(enabled = true, paused = false) { const root = await mkdtemp(join(tmpdir(), "queue-runner-")); roots.push(root); const repo = new LocalQueueRepository(root); await repo.writeSettings({ ...DEFAULT_QUEUE_SCHEDULER_SETTINGS, enabled, isPaused: paused, minimumFreeGb: 0 }); return repo; }

describe("queue batch runner", () => {
  it.each([[false, false, "QUEUE_SCHEDULER_DISABLED"], [true, true, "QUEUE_SCHEDULER_PAUSED"]] as const)("disabled/paused is a no-op", async (enabled, paused, expected) => { const result = await runNextBatch({ repository: await repository(enabled, paused) }); expect(result.run.safeMessage).toBe(expected); expect(result.results).toHaveLength(0); });
  it("continues a batch when one item fails and preserves 3-item claim", async () => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(9), queueDate: kst(now), now, dueNow: true }); const result = await runNextBatch({ repository: repo, now, preflight: readyPreflight, executor: async ({ items }) => items.map((item, index) => ({ queueId: item.id, productKey: item.productKey, passed: index !== 0, errorCode: index === 0 ? "ASR_FAILED" : "", finalVideo: index === 0 ? "" : `${item.id}.mp4`, reviewPath: "review.json", creativeScore: 90, videoQualityScore: 92, retryable: false })) }); expect(result.run.claimed).toBe(3); expect(result.run.completed).toBe(2); expect(result.run.blocked).toBe(1); expect(result.run.failed).toBe(0); expect(result.run.status).toBe("partial"); });
  it.each([[0, 3, 0, "success"], [1, 2, 1, "partial"], [2, 1, 2, "partial"], [3, 0, 3, "failed"]] as const)("records %i affiliate readiness defects without sibling corruption", async (invalidCount, completed, blocked, status) => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(9), queueDate: kst(now), now, dueNow: true }); const result = await runNextBatch({ repository: repo, now, preflight: readyPreflight, executor: async ({ items }) => items.map((item, index) => ({ queueId: item.id, productKey: item.productKey, passed: index >= invalidCount, errorCode: index < invalidCount ? "AFFILIATE_NOT_READY" : "", finalVideo: index < invalidCount ? "" : `${item.id}.mp4`, reviewPath: index < invalidCount ? "" : "review.json", creativeScore: index < invalidCount ? 0 : 90, videoQualityScore: index < invalidCount ? 0 : 92, retryable: false })) }); const items = await repo.items(); const successful = items.filter((item) => item.status === "video_ready_machine_qa"); expect(result.run).toMatchObject({ claimed: 3, completed, blocked, failed: 0, retried: 0, status }); expect(successful).toHaveLength(completed); expect(new Set(successful.map((item) => item.videoPath)).size).toBe(completed); expect(items.every((item) => !item.leaseOwner && !item.leaseExpiresAt)).toBe(true); expect(result.results.every((entry) => items.some((item) => item.id === entry.queueId && item.productKey === entry.productKey))).toBe(true); expect(QUEUE_SCHEDULER_FLAGS.PLATFORM_UPLOAD).toBe(0); });
  it("blocks before claim when runtime preflight fails and leaves queue attempts unchanged", async () => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(9), queueDate: kst(now), now, dueNow: true }); const result = await runNextBatch({ repository: repo, now, preflight: async () => ({ ...await readyPreflight(), ready: false, python: false, blockers: ["PYTHON_NOT_READY"] }) }); expect(result.run.status).toBe("blocked_preflight"); expect(result.run.safeMessage).toBe("RUNTIME_PREFLIGHT_BLOCKED"); expect(result.run.claimed).toBe(0); expect((await repo.items()).every((item) => item.status === "scheduled" && item.attemptCount === 0)).toBe(true); const recovered = await runNextBatch({ repository: repo, now: new Date(now.getTime() + 1), preflight: readyPreflight, executor: async ({ items }) => items.map((item) => ({ queueId: item.id, productKey: item.productKey, passed: true, errorCode: "", finalVideo: `${item.id}.mp4`, reviewPath: "review.json", creativeScore: 90, videoQualityScore: 92, retryable: false })) }); expect(recovered.run.claimed).toBe(3); expect(recovered.run.completed).toBe(3); });
  it("blocks before claim when any upload safety flag is true", async () => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(9), queueDate: kst(now), now, dueNow: true }); const result = await runNextBatch({ repository: repo, now, env: { SAFE_TO_UPLOAD: "true" }, preflight: readyPreflight }); expect(result.run).toMatchObject({ status: "blocked_preflight", safeMessage: "UPLOAD_SAFETY_FLAG_BLOCKED", claimed: 0 }); expect((await repo.items()).every((item) => item.status === "scheduled" && item.attemptCount === 0)).toBe(true); });
  it("replaces a product-specific hard failure from reserve without changing the logical slot", async () => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(12), queueDate: kst(now), now, dueNow: true }); const calls: string[][] = []; const result = await runNextBatch({ repository: repo, now, preflight: readyPreflight, executor: async ({ items }) => { calls.push(items.map((item) => item.productKey)); return items.map((item, index) => ({ queueId: item.id, productKey: item.productKey, passed: calls.length > 1 || index !== 0, errorCode: calls.length === 1 && index === 0 ? "ASR_FAILED_AFTER_REPAIR" : "", finalVideo: `${item.id}.mp4`, reviewPath: "review.json", creativeScore: 90, videoQualityScore: 92, retryable: false })); } }); expect(result.run.claimed).toBe(3); expect(result.run.completed).toBe(3); expect(result.run.metrics.fallbacks).toBe(1); expect(calls[1]).toHaveLength(1); const slot = (await repo.items()).find((item) => item.queueRank === 1)!; expect(slot.slotId).toBe("slot-001"); expect(slot.productCandidateAttempt).toBe(2); expect(slot.candidateHistory).toHaveLength(2); expect(slot.candidateHistory[0].outcome).toBe("replaced"); expect(slot.candidateHistory[1].replacementOfProductKey).toBe("p0"); });
  it("isolates hook-family exhaustion to one slot and recovers only that slot", async () => { const repo = await repository(); const now = new Date(); await repo.insertRanked({ ranked: ranked(12), queueDate: kst(now), now, dueNow: true }); const calls: number[] = []; const result = await runNextBatch({ repository: repo, now, preflight: readyPreflight, executor: async ({ items }) => { calls.push(items.length); return items.map((item, index) => ({ queueId: item.id, productKey: item.productKey, passed: items.length === 1 || index !== 1, errorCode: items.length === 3 && index === 1 ? "CREATIVE_SELECTION_FAILED" : "", finalVideo: `${item.id}.mp4`, reviewPath: "review.json", creativeScore: 90, videoQualityScore: 92, retryable: false })); } }); expect(calls).toEqual([3, 1]); expect(result.run.completed).toBe(3); expect(result.run.metrics.fallbacks).toBe(1); });
  it("returns overlap safe no-op", async () => { const repo = await repository(); const release = await acquireProcessLock(join(repo.root, "runner.lock"), "other", 60_000); try { const result = await runNextBatch({ repository: repo }); expect(result.run.safeMessage).toBe("SCHEDULER_ALREADY_RUNNING"); } finally { await release(); } });
  it("promotes only exact executor-receipt evidence and reports terminal Codex completion", async () => {
    const repo = await repository(); const now = new Date();
    await repo.insertRanked({ ranked: ranked(9), queueDate: kst(now), now, dueNow: true });
    const result = await runNextBatch({ repository: repo, now, preflight: readyPreflight, executor: async ({ items }) => {
      const reviewPath = join(repo.root, "batch-review.json");
      await writeFile(reviewPath, `${JSON.stringify({ version: "autonomous-video-review-v2", visualReviewExecuted: true, finalAutomatedQaPassed: items.length, items: items.map((item) => ({ productKey: item.productKey, status: "AUTO_QA_PASS", machineQaPassed: true, finalAutomatedQaPassed: true, visualReviewExecuted: true, blockers: [], publishReady: false, SAFE_TO_UPLOAD: false, SAFE_TO_PUBLIC_UPLOAD: false })) })}\n`);
      return Promise.all(items.map(async (item) => {
        const videoPath = join(repo.root, `${item.id}.mp4`); await writeFile(videoPath, `video-${item.id}`);
        const evidence = await createTestCodexEvidence({ operationNamespace: basename(repo.root), queueId: item.id, productKey: item.productKey, videoPath, reviewedAt: now, reviewResult: "pass", sourceReviewArtifact: reviewPath, notes: "Fresh authenticated executor review passed the exact bound visual evidence.", receiptRoot: join(repo.root, "receipts") });
        return { queueId: item.id, productKey: item.productKey, passed: true, errorCode: "", finalVideo: videoPath, reviewPath, creativeScore: 90, videoQualityScore: 92, retryable: false, machineQaFinishedAt: now.toISOString(), codexReview: { status: "pass" as const, errorCode: "", retryable: false, attempts: 1, deduplicated: false, receiptPath: evidence.reviewReceiptPath, evidence } };
      }));
    } });
    expect(result.run).toMatchObject({ status: "success", completed: 3, safeMessage: "BATCH_CODEX_REVIEW_COMPLETE" });
    expect((await repo.items()).filter((item) => item.status === "video_ready_autoqa")).toHaveLength(3);
  });
});
function kst(date: Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Seoul" }).format(date); }
async function readyPreflight(): Promise<QueueVideoRuntimeReadiness> { return { ready: true, assetRoot: true, python: true, pythonVersion: "Python 3.10", whisperXRuntime: true, ttsCommand: true, asrPython: true, asrScript: true, asrModel: true, ffmpeg: true, ffprobe: true, diskSpace: true, durationMs: 1, blockers: [], configured: { assetRoot: true, python: true, ttsCommand: true, asrPython: true, asrScript: true, asrModel: true }, SAFE_TO_UPLOAD: false }; }
function ranked(count: number): RankedLiveProduct[] { return Array.from({ length: count }, (_, i) => ({ candidate: { candidateId: `c${i}`, productKey: `p${i}`, rawProductId: `${i}`, rawProductName: `상품${i}`, canonicalProductName: `상품${i}`, productAliases: [], productAnchors: [`상품${i}`, "정리"], useCase: i % 3 === 0 ? "vehicle_organization" : i % 3 === 1 ? "desk_organization" : "laundry_drying", category: "생활", categoryPath: "생활", priceText: "1", rawProductUrl: `https://www.coupang.com/${i}`, selectedAffiliateUrl: `https://link.coupang.com/${i}`, productImageUrls: [`https://image/${i}`], sourceProvider: "coupang_partners_product_search", sourceRequestId: `r${i}`, discoveredAt: new Date().toISOString(), sourceKeyword: "정리", eventContext: { eventId: "e", eventName: "e" } }, score: { productKey: `p${i}`, eventRelevanceScore: 1, motionSuitabilityScore: 1, policySafetyScore: 1, imageReadinessScore: 1, affiliateReadinessScore: 1, duplicatePenalty: 0, usageEvidenceScore: 1, finalProductScore: 90, selectionRank: i + 1, eligible: true, blockers: [] } })); }
