import { describe, expect, test, vi } from "vitest";
import { generateDeterministicCreativeCandidates } from "@/lib/video-automation/creativeCandidates";
import { runProductToVideoPipeline } from "@/lib/video-automation/pipeline";
import type { PipelineDependencies, ProductVideoAutomationInput } from "@/lib/video-automation/types";

const input: ProductVideoAutomationInput = { runId: "run", product: { productKey: "desk-cable", rawProductName: "케이블 정리함", canonicalProductName: "케이블 정리함", aliases: ["선 정리함"], anchors: ["케이블", "정리", "책상", "고정"], category: "전자액세서리", imagePaths: ["1", "2", "3", "4", "5"] }, creative: { candidateCount: 3, language: "ko" }, mode: "local_review_only" };
function deps(): PipelineDependencies { return { generateCandidates: vi.fn(async (value) => generateDeterministicCreativeCandidates(value)), synthesize: vi.fn(async () => ({ audioPath: "voice.wav" })), validateAsr: vi.fn(async () => ({ passed: true, similarity: 0.95, transcript: "케이블 정리 책상 고정", recognizedAnchors: input.product.anchors })), align: vi.fn(async () => ({ words: [{ word: "케이블", start: 0, end: 0.3, confidence: 0.9 }, { word: "정리를", start: 0.31, end: 0.7, confidence: 0.9 }] })), render: vi.fn(async () => ({ outputPath: "output.mp4" })), qa: vi.fn(async () => ({ passed: true, blockers: [] })) }; }
describe("product-to-video pipeline", () => {
  test("binds selected script through TTS, ASR, captions, render and QA", async () => { const dependency = deps(); const result = await runProductToVideoPipeline(input, dependency); const selected = result.selection.candidates.find((entry) => entry.selected)!.candidate; expect(dependency.synthesize).toHaveBeenCalledWith(selected.script); expect(dependency.render).toHaveBeenCalledWith(expect.objectContaining({ selected })); expect(result.status).toBe("COMPLETED"); });
  test("all failed candidates block TTS and render", async () => { const dependency = deps(); dependency.generateCandidates = vi.fn(async (value) => generateDeterministicCreativeCandidates(value).map((candidate) => ({ ...candidate, script: `${candidate.script} 무조건 100% 보장합니다.` }))); const result = await runProductToVideoPipeline(input, dependency); expect(result.status).toBe("CREATIVE_SELECTION_FAILED"); expect(dependency.synthesize).not.toHaveBeenCalled(); expect(dependency.render).not.toHaveBeenCalled(); });
  test("QA failure is never completed", async () => { const dependency = deps(); dependency.qa = vi.fn(async () => ({ passed: false, blockers: ["QA_FAILED"] })); const result = await runProductToVideoPipeline(input, dependency); expect(result.status).toBe("MANUAL_REVIEW"); expect(result.SAFE_TO_UPLOAD).toBe(false); });
});
